### ISSUE TITLE
gold shovel modes (bedrock to sky/cuboid)

### ISSUE THREAD

**Issue by hunter688** [MinecraftPortCentral/GriefPrevention#108]
Situation:

Default behavior for claims want create from bedrock to sky, similar for subclaims.

In some cases will be fine set showel to another mode and allow set cuboid area using selected block and make not bedrock to sky claims/subclaims.

Example:

spawn admin claim from bedrock to sky, subclaim area 40x20x20 for mines, where would like allow block-break

**Comment by inklit** [comment]
I can imagine why this would be a good idea.
I will another example here:
A player on my server created an apartment complex, with multiple stories.
In order to give users access to their room, he creates a subdivision.
In the current non-cuboid mode, this will give the particular player access to all of the apartments above and below his floor.

The apartment complex owner with a cuboid mode system would be able to create a subdivision that is only for a specific room, disregarding the floors above and below from the subdivision. This would prevent the user from griefing the floors above and below his apartment room.

I support this suggestion.
