### ISSUE TITLE
Add general use meta/damage data support to flags....

### ISSUE THREAD

**Issue by majix560** [MinecraftPortCentral/GriefPrevention#132]
Add general use meta/damage data support to flags that take an item or block name/id as a target.
A lot of mods are programmed to have items/blocks share item names/ids but with different meta/damage data to differentiate between them.
And no, that includes stuff that's completely different and/or completely unrelated.
Take Vazkii's Psi mod for example.
All of the components of a specific type share the same item name/id with only meta/damage data to differentiate them.
It makes far more sense to have generalized support for meta/damage data tags in the item names/ids then to hard code support for all of the various mods' items/blocks as options to use in the "[]" brackets.

**Comment by bloodmc** [comment]
> It makes far more sense to have generalized support for meta/damage data tags in the item names/ids then to hard code support for all of the various mods' items/blocks as options to use in the "[]" brackets.

Blockstates are NOT hardcoded as they have been the standard since 1.8 and will not be going away. Every single mod is required to use blockstates for blocks in 1.8+.

To handle blocks in GP, you simply specify the [property=value] after the flag. However, non item blocks are still an issue as damage value seems to still be the the only thing that can be used to distinguish an item from another of the same type. I'll add support for meta soon. Just keep in mind that this will be changed the moment Mojang adds a similar system to blockstates for items.
