### ISSUE TITLE
Trust, Adminclaims and Fire

### ISSUE THREAD

**Issue by SnowBlitzz** [MinecraftPortCentral/GriefPrevention#16]
After a player has been trusted with /gp trust, he/she should be able to build and break inside the claim however they are not able to break and can only place certain blocks (haven't found out why yet)

/gp adminclaims does not work, it asks me to select a corner but when I select an opposite corner it does not register. The only way around this is to claim it yourself then do /gp transferclaim, but this only makes the claim an adminclaim temporarily until server restarts.

I set firespread in the config to false, instead of preventing firespread it prevents fire placement, both inside and outside of claim.

Version I'm using is the latest one you've sent griefprevention-12.7.1-SpongeTest-B2

**Comment by bloodmc** [comment]
@SnowBlitzz Please test my latest build as there have been many changes since the B2 build.

https://www.dropbox.com/s/aceg1ir810125pb/griefprevention-12.7.1-SpongeTest-B3.jar?dl=0

You will need to wipe out all GriefPrevention data as I changed configs and how data is generated. In each world folder, just wipe out the GriefPrevenionData folder and in the ./config folder, wipe out the GriefPrevention folder then retest. Please check my latest commits for information regarding what changed.

**Comment by SnowBlitzz** [comment]
Will the 'configs and how data is generated' be changed again in the future? Just wondering so we don't have to keep reclaiming land after each update XD

**Comment by bloodmc** [comment]
@SnowBlitzz I'll let you know if it does. It usually doesn't happen but there were major fixes I had to do yesterday which required moving things around to make everything flow better. Of course, after I release the plugin, any data changes will have a conversion script =).

**Comment by bloodmc** [comment]
@SnowBlitzz The following commit has trust and untrust support. Keep in mind that it is not the same as Bukkit version so read the commit mesage.

https://github.com/MinecraftPortCentral/GriefPrevention/commit/9f70284075d6d8b964fc669e57d38dee9fc022d9

**Comment by SnowBlitzz** [comment]
Ahh I see, first little steps to a whole new commands system

* Removed internal permission support in favor of permission plugins such
as PEX.
* Cleaned up the default permission check logic.
What does these two mean by the way?

**Comment by bloodmc** [comment]
GriefPrevention had a basic permission system that it used in Bukkit version. Since I added support with PEX, I removed the internal system as it is no longer needed.

Please test latest build here for trust/untrust

https://www.dropbox.com/s/pvaohc9wipe409u/griefprevention-12.7.1-SpongeTest-B5.jar?dl=0

To trust a player
'/gp claims trust <playername>'

To untrust
'/gp claims untrust <playername>'

Note: standing inside claim trusts that claim, standing outside trusts all.

**Comment by SnowBlitzz** [comment]
http://puu.sh/oiNOc/c318f3c375.png
The messages need to be reworked too I guess

**Comment by SnowBlitzz** [comment]
Both /gp claims trust and /gp claims untrust gave me an error
Unknown command. Try /help for a list of commands
Looks like the commands were not registred, /gp help broken too

**Comment by bloodmc** [comment]
@SnowBlitzz I'm not having this issue. It sounds like the plugin didn't load. Wipe out ALL GriefPreventionData and try again.

**Comment by bloodmc** [comment]
Fire spread has been fixed in commit 
https://github.com/MinecraftPortCentral/GriefPrevention/commit/624b3f7708fe8b1adc34b514c2c10d645992f2b0

Adminclaims were fixed previously so I'm now closing this issue as everything seems to be resolved.
