### ISSUE TITLE
Town features wanted

### ISSUE THREAD

**Issue by nguyenquyhy** [MinecraftPortCentral/GriefPrevention#166]
To implement a town protection, I need some additional capabilities in GP.

Here is my scenario:
(1) I want to protect a large town area with admin claim.
(2) Inside the town area, I want to create a subdivision for each empty house slot.
(3) I want any player to be able to visit the town and create their own claim inside the empty house slots without requiring actions from admins.

(1) and (2) above can already be done using current GP with claim and subdivisions. However, (3) will requires some additional features:
- A claim level below subdivision (sub-subdivision?). Or maybe even better if GP would remove the whole subdivision concept and allow any hierarchy of claim (a claim can be created inside any existing claim and may inherit perm and flag, a depth limitation may be enforced to ensure server performance).
- A new claim flag to allow creating sub-claim. As discussed in Discord, this flag should be "true for all" for wilderness and default to "owner only" for normal claims.

**Comment by nettyneets** [comment]
It would be great to at least be able to transfer subdivisions (maybe make it a seperate /plot) so that you can use /transferclaim to give the claim to someone else, which would then credit you back with the blocks spent and use up the new owners claim blocks instead. It would of course need to check that the player in question has enough claim blocks available for the /transferclaim to go through. As for flags I think it would be enough for them to reset to the standard player claim config (server specific-eg global overrides staying intact).

I think being able to claim subdivisions/"plots" without the claim owner's/admin's action should be optional, because if let's say a player makes a town on the server, they might have criteria for allowing players to join the town or they might not want "troublemakers" claiming one of the plots.

**Comment by bloodmc** [comment]
@nguyenquyhy @nettyneets I'm thinking of doing the following

1. Remove subdivisions. Instead, you will simply create a "sub-claim" that can be transferred to a new owner (essentially selling part of your land). This would allow players to claim a large area then start to sell pieces of it for a price. As for selling, this would need to be discussed on how the sale should take place. I'm open to ideas.

2. Allow sub-claims to have children claims with no depth limit.

Thoughts?

**Comment by nettyneets** [comment]
I think with regards to selling it would be good to have two options:
1) Open sale - let the player selling the claim set a price, and have some sort of chat notification letting you know that the claim is for sale, and the claim's price when you enter it. That way anyone could buy the claim by running a command without the seller's action.
2) Closed sale - let the owner put the claim up for sale and set a price, and have a chat notification like "This claim is available for purchase for $100  from (owners name). Please contact them to buy it." Then they could run a command to sell the claim to a chosen player.

**Comment by inklit** [comment]
@bloodmc I think this is an interesting idea; perhaps claims in the wilderness claim should also be considered "sub-claims" of the wilderness. This hierarchy would be much more organized.

In regards to selling, @nettyneets pretty much summed it up.

**Comment by inklit** [comment]
@bloodmc and I were discussing this in Discord. Here is the points we discussed. 

The plan for now is to allow you to create a new subclaims inside of subclaims. This would just set the claim parent to the subclaim that is above it. 

Trivial by itself, but there is more specifics and logic that needs to be thought about here to facilitate towns.

## Town Creation
To create a town, you should simply be able to create a large claim.
This large claim should be able to be resized in the future to expand your town.
Once you own this large claim, you will be able to create subclaims that are capable of being transferred away.

## Claim Transferring
To explain my ideas better here, I will give you a scenario similar to the one @bloodmc gave in Discord.

**Scenario**
Say Player A is the founder of GPTown. GPTown's claim is worth 1,000 blocks.
Player B wants to live in your town, so you create him a subclaim in GPTown's large claimed area that is sized 100 blocks. You then transfer the subclaim's ownership to Player B.

**How is the claim block count dealt with here?** 
My suggestion is that Player B's available claim blocks is reduced by 100 and Player A's available claim blocks is increased by 100. 
The size of GPTown is now 900 blocks, but 1,000 cumulative. 

Player A no longer has access to the subclaim that he transferred ownership of, and he is not responsible for it's claim blocks.

## Claim deletion/unclaiming or Town disbandment
This is a quite important one to talk about because it has the capability of completely destroying a town.

Essentially, a subclaim that does not belong to the upper claim owner should become an independent claim if the upper claim is deleted. This "new" claim will be just like a normal claim that is created in the wilderness. Any subclaims of the said subclaim will still belong to it, unless it is disbanded and then the cycle begins again.

If Player A unclaimed GPTown's claim, he would receive 900 claim blocks and not 1,000 because 100 of the claim blocks are part of a subclaim that will soon become it's own upper level claim.

## Claim Visualization
When dealing with infinitely recursive claims, it needs to be possible to differentiate upper/lower level claims from eachother.

My suggestion for this is to cycle through wool colors.
If you run out of wool colors in the claim corners while visualizing, it will just start from the beginning again. By time you run out of wool colors, it should be very obvious to differentiate the first set of colors from the second set. They should be far enough apart to tell.

**Please leave your opinions.**

**Comment by bloodmc** [comment]
@nguyenquyhy @nettyneets @inklit @LemADEC @KumaGetsu @Vauxite @Mohron @Eufranio @OblivionNW @lightningo7 @IBGnova @hunter688 @5igm @Nentify @Karaga

Please discuss above as I plan on implementing town features as soon as everyone agrees on how this should all be setup.

**Comment by lightningo7** [comment]
I like the idea of what is presented however I do see some issues coming up.

Going back to the GPTown example let's say Player A is the founder of the town, he wants to control what people do and sets up a rule board saying that members can not use redstone devices in their claims or the member will be kicked out. 
Player B joins the town, and is given his claim, at which point he decides to make a redstone device, but Player A does not want this. If the claim is "given" to the resident of the town there is no way to enforce such things.

However, it may be a good idea to restrict certain kinds of access to the claim, E.G. chest and furnace access for privacy's sake.

**Comment by hunter688** [comment]
And you'll have time for development SpongeForge @bloodmc ? Any dev helps you with this major feature of GP ? I prefer fixing major bugs in the server core instead adding new features to plugin which works very well.

**Comment by Vauxite** [comment]
I believe that people who like the town-approach prefer a more RPG like system. What's proposed is just a limited version of the default system.

**How is the claim block count dealt with here?**
- A town should be assigned x players worth of blocks at creation.
- All players generation of claim blocks are pooled to the town itself. There should a bonus factor for having more residents in the town.
- Leaving a town means leaving your claimed blocks. This may sound harsh, but I believe this fit the theme.
- There should be a limit on the amount of total accumulated claimblocks. Most likely by number of residents. 

 **Claim deletion/unclaiming or Town disbandment**
- The town owner should never have the power to disband the town. As long as the town has residents one of them will be appointed as the new owner. Perhaps by amount of time spent in that town.
- The town owner should be able to  reclaim any subdivided claim/plot. Should be sort of configurable eviction notice.
- The town owner should be able to force flags for the whole town.
- If everyone leaves a town, all accumulated claimblocks in that town will be lost.

**Comment by IBGnova** [comment]
So what happens if "Player B" disbands his claim? I do like the idea stated above where if you leave the claim you will lose your claim blocks, as I see that being the only way to do it unless you make a sort of "Town Claim Blocks Bank" where all the claim blocks for the town are stored. 

What about Town Ranks, will this be like every other town plugin where you can appoint people to manage certain aspects of your town? Will the town owner have access to change flags within each players claim? If so will these be things we can (as server owners) determine what they can/can't edit within each "Town Member's" claim? 

Will there be any sort of income or any incentive for a player to want to start a town other than to have a community? Would it be possible to add a feature that allows a sort of tax or an ability to sell claims rather than just "Transfer" them? I support both, but I would find it quite different if there was a sort of percentage cut that the Town Owner takes from each player (most likely defined in the config for all towns). Also would there be a price for the town, something like town upkeep?

And then going back to the editing of claims, would it be possible to trust a member to one area rather than to trust them to the full claim. So if you had a town hall or something of the sort could you make it so all players within your claim could access that area (not sure if this is already possible I don't mess with subdivisions much.)?  

Would all of this be supported by 3D claims as well? I could see my players making some quite amazing towns with vertical buildings or even a hotel structure. :P 

Will there be a town chat (a channel for town members to communicate without speaking in public chat)?

Will there be a cap on how many players can be in one Town, if so what will this be determined by. I would suggest the amount of claimed blocks the town has, maybe 10x10 per person (The starting amount of claim blocks by default)?

If I think of anything else I will just edit this post instead of making another.

**Comment by LemADEC** [comment]
Sounds like Towny style grief prevention to me, which is good but implies a few things:
- town ranks: allow players to progress in the town hierarchy and gain new power/responsibilities
- nations: allow towns to regroup (probably not initially)
- taxes/rent periodically due to the mayor for your claim (claim upkeep) in addition to a 'buy' price
- taxes/rent periodically due to the server for your town (town upkeep) in addition to a 'buy' price

I think sub-sub-sub-claims is relatively complex to understand and represent for players. I would suggest a proper configurable naming to differentiate them and just stick to 2 layers (town > claims), maybe 3 (town > neighborhood > plot or town > building > flat).

When a town mayor is offline for too long, town shouldn't disappear. Instead, town should remain as we don't want instant griefing or something in a community driven area. Staff would be notified on login of a 'MIA mayor' and can then name a new one.
Same goes when a claim owner goes MIA, the mayor is informed and should be able to deal with it.

We could allow residents to elect a new mayor, maybe through an addon of sort.

Mayor should be able to force flags on all subclaims, independently of the town flags (for example: allow mob spawning in the town, not in the claims).

**Comment by inklit** [comment]
I disagree with the suggestions @LemADEC made because GriefPrevention is supposed to be controlled by the players and fully self sufficient without staff action. On top of that, the points made about complexity are irrelevent as most people wont go that deep.

**Comment by Nentify** [comment]
I don't really agree with this being in GP at all. If anything, I'd try cutting down GP to just land protection without "spam protection" and any other bloat. Perhaps move those features into another plugin.

**Comment by inklit** [comment]
@Nentity at the very least, subclaims need to be allowed inside of other subclaims.

I agree with you,  though,  another plugin that use GriefPreventions API should be for town specific mechanics.

**Comment by bloodmc** [comment]
@Nentify these features won't alter the way GP works at all. I will simply make a new type of claim called "TOWN" that will enable these features. If you don't want any town features then you simply don't give permission to create towns.

**Comment by Rasgnarok** [comment]
> All players generation of claim blocks are pooled to the town itself. There should a bonus factor for having more residents in the town (this will act as incentive to have a town).
This, I agree with - players joining under a single leader's claim - a town, team, whichever you wish to call it, should have shared claim ressources. The idea is to make players group together, if they so want. If not, they can create their own claim which they can use the standard system for - with /trust as the only way to share it.

> The claimedarea owned by residents will always be defined by town owner. Having subsubdivide claims adds a layer of unneeded complexity.
I disagree - there should be a way to divide the main claim, but the subdivide system would not be it. As discussed in the Discord, there should not be subdivides at all - leave those to singular or admin claims, and simply have two layers {TOWN[PLOT]} - where PLOT can be sold off (as per @nettyneets's idea, or leased and open for claiming). Issue I see with this is, the claiming of these plots should only be possible for members of the TOWN, and so owning claims within the main claim is seperate from being a member of the TOWN.

Side note, the neat idea of having the TOWN name as a user chat prefix would help enforce and propagate the usage - those of us moving off of towny-like Polis would find the task easier.

**Comment by bloodmc** [comment]
Google doc should be editable now.

**Comment by bloodmc** [comment]
@nguyenquyhy @nettyneets @inklit @LemADEC @KumaGetsu @Vauxite @Mohron @Eufranio @OblivionNW @lightningo7 @IBGnova @hunter688 @5igm @Nentify @Karaga

http://i.imgur.com/R2bTeKU.jpg

Core code for town support is nearly done =)
