### ISSUE TITLE
Pumps can't interact and aren't listed in the /trust

### ISSUE THREAD

**Issue by Eufranio** [MinecraftPortCentral/GriefPrevention#191]
I have a IC2 and ImmersiveEngineering pumps. When i place them and supply with energy, they won't work inside a claim. I can't use /trust #[IC2] because it is not listed as fake player, and that player isn't online.

**Comment by bloodmc** [comment]
In order to fix this, both IC2 and ImmersiveEngineering will need to fire Forge's FluidEvent which can be found here

https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fluids/FluidEvent.java

I already spoke to @Aroma1997 who plans to add these events in a few weeks when he gets more time. I would log a ticket for IE to get this done as well and any other mods that make use of fluids.

**Comment by bloodmc** [comment]
@Eufranio Please provide a test world with pumps setup.

**Comment by Eufranio** [comment]
Pumps are fixed using latest SF+GP, I can't reproduce the bug anymore.
