### ISSUE TITLE
Plethora Laser item is able to catch mobs on fire

### ISSUE THREAD

**Issue by inklit** [MinecraftPortCentral/GriefPrevention#223]
Using GP 1.10.2 163, SF 1928, Plethora 1.0.0-beta3, ComputerCraft 1.8pr0, CCTweaks 1.2.4, and unborked-CC 1.0.4.

When shooting a laser beam at a mob inside of a claim, the mob is still caught on fire.

Additionally (however this is Plethora's fault I think) players can be caught on fire, too, even if PVP is off.

The Laser entity is an IProjectile, which is probably why.

**Comment by SquidDev** [comment]
> When shooting a laser beam at a mob inside of a claim, the mob is still caught on fire.

The issue is that `EntityLaser` does not extend `EntityThrowable` as it does unwanted things. Consequently `SpongeCommonEventFactory.handleCollideImpactEvent` is never fired, and so `CollideEntityEvent` is never fired.

I guess I could invoke `handleCollisdeImpactEvent` conditionally from my code, and cancel if it fails. Whilst it may not be the most elegant of solutions, it should mean it interacts with Sponge correctly.

There is an `IgniteEntityEvent` event, but I couldn't find where it was fired within Sponge code and I don't think GriefPrevention handles it: I might have missed it though.

**Comment by inklit** [comment]
bloodmc and I found out that it's only Skeleton Horses that are affected by this. 
I don't know why I did not test other mobs earlier, my apologies...I'll try to test more vigorously in the future haha.
