### ISSUE TITLE
Pixelmon -- Subdivided ContrainerTrust -- Pokeballs through floor

### ISSUE THREAD

**Issue by Fiammata** [MinecraftPortCentral/GriefPrevention#377]
Hello! I have read the wiki and I have found:

> Example 2

> To allow Pixelmon Pokeballs to interact with any blocks in all basic claims, has to be run while standing in a basic claim.

> /cf projectile-impact-block pixelmon:occupiedpokeball any true override

Unfortunately this command doesn't seem to help with a Subdivided claim, in which a user has ContainerTrust. In Pixelmon, the pokeball shoots through the floor for a regular player. The pokeball works normally for the claim owner, and for the staff. It does not work for passing visitors. It does not work for those with ContainerTrust.

Apologies, but I don't believe I have access to fml-server-latest.log and I do not have code perms on the server.

What is the proper way to make the pokeballs work for anyone and everyone?

Thank you for your time.

**Comment by bloodmc** [comment]
@Fiammata Subdivisions inherit from parent claims by default. If you want a subdivision to act on its own then you need to turn InheritParent off in /claiminfo options or set the flag in parent. Also make sure you are running latest GriefPrevention, SpongeForge and LuckPerms. If it still turns out to be an issue, let me know but I will need to see the "fml-server-latest.log" to assist further.
