### ISSUE TITLE
Crash on passive server standing

### ISSUE THREAD

**Issue by Foxgreat** [MinecraftPortCentral/GriefPrevention#520]
[crash-2017-11-13_03.40.04-server.txt](https://github.com/MinecraftPortCentral/GriefPrevention/files/1466333/crash-2017-11-13_03.40.04-server.txt)

Hello i have an crash on GriefPrevention, i hope it helps you figure out what is this
MC 1/12/2
Forge 2529
Sponge 7/0/0 - 2730
GriefPrevention 4.3.0.470

**Comment by Rasgnarok** [comment]
Your Luckperms, GriefPrevention and Spongeforge are all outdated. Please update to receive support. Furthermore, note that your server crashed because of the Server Watchdog, which in itself isn't necessarily the issue. In your `server.properties` , set the `max-tick-time` to `18000`. Bigger periods of timeout will prevent common crashes, but there's still something causing the timeout... so please provide the `fml-server-latest.log` that matches the server-session before the crash.

**Comment by bloodmc** [comment]
Do as Rasgnarok suggested and also disable fire spread as that seemed to cause the deadlock. You can achieve this by disabling the gamerule with
```
/gamerule doFireTick false
```
