### ISSUE TITLE
Claims ingnoring config and denying ANY event

### ISSUE THREAD

**Issue by TrueNightPhoenix** [MinecraftPortCentral/GriefPrevention#577]
The server is using:
ModPack: ATM3 5.7c (issue persisted in 5.6)
FTBServer-1.12.2-14.23.1.2585-universal
GriefPrevention-1.12.2-4.3.0.524
SpongeForge-1.12.2-2555-7.1.0-BETA-2842

Plugins (20): (Listed but not really plugins: Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge), AdamantineShield, BetterChunkLoader, CatClearLag, Discord Bridge, Enjin Minecraft Plugin, GoonUtils, GriefPrevention, LuckPerms, NuVotifier, Nucleus, PlayerShopsRPG, ProjectCore for SpongeAPI 7.x, SeriousVote, StackBan for SpongeAPI 7.x, Total Economy
also a string of random letters and numbers, tell me if you need that

Issue:
Sometimes, seemingly without any cause other than the server online time (but it even happened when the server just restarted), the griefprevention plugin will just deny any event inside the claim: liquids will not flow, itemStack creation will not happen, entire mods like Botania will completely stop working, OreExcavation will not work (vein miner), mob grinders will not work and mobs will just stack up (also creating tps drops), sometimes this will solve itself in some time, 1-2 times it solved itself in 20-30 minutes, other times the server needs to be restarted, this also seems to be happening on the Direwolf20 1.12 server of this network, if you want the details on that server too tell me.
This also bypasses any config flags, for example liquid flow is enabled in the config

Other than that the player can still pretty much do anything involving itself, extract-insert itemstacks from containers etc...

Tell me if you need any other kind of information.
Thanks

PS: sorry for eventual grammatical errors

**Comment by bloodmc** [comment]
This makes no sense....GP will never just deny ALL events. If this is happening on your server then it is clearly lagging and is being caused by something else. Run a profiler and/or sponge timings to figure out the cause.

**Comment by TrueNightPhoenix** [comment]
i don't think you understand, sometimes this happened with a tps of 20 and nothing lagging AND everything working outside the claims, don't close issues like this

**Comment by bloodmc** [comment]
You don't understand how events work at all. If you want to know what GP is checking then use the debugger

https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Debugging

**Comment by Whazaaaaa** [comment]
So I'm having this problem. I just did /gpdebug for a while. Placed some water which doesnt flow while claimflag for flow is on true.
https://gist.github.com/anonymous/3116d486383a35eeac99fb83b9422a1c
Does that help?
Tps is also 20 so Its not lagg from what I can tell.
From what I can tell this started happening after updating from 4.3.0.511 like a week ago or something
Could it break anything if I went back to that version?

**Comment by Whazaaaaa** [comment]
Or what could be the earliest version I could go back to safely?

**Comment by bloodmc** [comment]
Reproduce on a clean server with ONLY LP/GP/SF and provide steps.

**Comment by Whazaaaaa** [comment]
Yeah the whole problem is that I dont know what the initial cause is for GP to break like this. I'll investigate further. I get you cant really help with a vague explenation like this. :(

**Comment by bloodmc** [comment]
According to GP's debug log, flowing_water is TRUE for your username which means GP isn't blocking anything. For a better log, set a username filter.

**Comment by Whazaaaaa** [comment]
It might be true but the water isnt flowing inside the claim. Outside its fine.
https://gist.github.com/anonymous/f7a78290bbf3d1c0aa131fe560177715
http://prntscr.com/i54cup

**Comment by Whazaaaaa** [comment]
Also http://prntscr.com/i54e68

**Comment by bloodmc** [comment]
OK so it places but doesnt flow after that? Create a new claim and retest with no user filter.

**Comment by bloodmc** [comment]
Join GP's discord https://discord.gg/RhPgdD

**Comment by DrZoddiak** [comment]
I looked into this a bit (and went over my findings in the discord a tad)
It appeared to me that the liquid-flow flag was actually being ignored for the most part.

I started a fresh world/server with:
**Forge** - forge-1.12.2-14.23.1.2604-universal
**SpongeForge** - 1.12.2-2555-7.1.0-BETA-2847
**GP** - griefprevention-1.12.2-4.3.0.526
**LP** - LuckPerms-Sponge-4.0.117
and **only** those, no other mods or plugins

I set the wilderness liquid-flow flag to true and tried placing a water block as a user (griefprevention.user) and reloaded the server with gpreload, and the water did not flow.

I did the same but with administrator permissions (griefprevention.admin & griefprevention.user) and used gpreload, but now the water flowed.

**Debug of both events (no user filter)**
https://gist.github.com/anonymous/56a0fc3095d07d8ca7abe0cc6f3c84e4

**FML-Junk (because of 1.12)**
https://gist.github.com/DrZoddiak/8a65825154b11dca1d60c7aad21151b2

**FML-latest (just in case you need it)**
https://gist.github.com/DrZoddiak/da0d9a243bbcb9dc8c9cb1c0f046cd8f

**Latest (also just in case) **
https://gist.github.com/DrZoddiak/f00f22f21ce0682a26b8f2a397a64a7c

**Picture of flag**
https://imgur.com/a/vkZtN


Let me know if you need anything else.
