### ISSUE TITLE
Claimed entities don't dissapear after owner inactivity

### ISSUE THREAD

**Issue by MithrandirCraft** [MinecraftPortCentral/GriefPrevention#605]
Protected entities are still protected after the claims dissapear and the owner is long gone.
They should also be unclaimed after a certain owner inactivity, just like terrains.

Spigot:  CraftBukkit version git-Spigot-4bd94dc-4a03053 (MC: 1.12.2)
GP: 16.7.1

**Comment by bloodmc** [comment]
@MithrandirCraft This repo is for the Sponge version of GP. Your issue is caused by this code

https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L920-L965

It has nothing to do with claims expiring as tamed entities store their owner with their data. All GP is doing is checking to see if the owner matches the attacker and if not denies it assuming the other checks passed. One fix could be to check if the owner has been active recently and if not allow the attack to occur. But this would be a discussion with the GP Bukkit devs.

Report it to https://github.com/TechFortress/GriefPrevention/issues

**Comment by MithrandirCraft** [comment]
Appollogies for the mistake.
