### ISSUE TITLE
piston flags not working

### ISSUE THREAD

**Issue by Shmeeb** [MinecraftPortCentral/GriefPrevention#653]
i'm still having this issue of piston farms not working, this is my debug https://gyazo.com/0f9f6928e651cfa0f56cb4a162095bc3

shouldn't 
/cf block-break minecraft:piston any true override
take care of it?

/cf block-break minecraft:piston minecraft:piston true override
/cf block-break minecraft:piston minecraft:air true override
also doesn't work

awhile ago you said to try using metadata but that doesn't even go through https://gyazo.com/e38e36bd4cee7e97fe126ed86a971b2c
/cf block-break minecraft:piston.4 minecraft:piston true override

**Comment by kencinder** [comment]
I encountered something like this with a redstone circuit controlling a moving "wall" from a pressure plate, in an Admin claim. The problem appears to be that whoever steps on the plate, is considered to be the one moving the pistons judging by the debug.

When I had a regular user activate the circuit, the pistons would retract...and stay there, even though they worked fine for me. It's because they don't have permission for block break/place, and the pistons are working as the user that activated the pressure plate. Why they moved the blocks in a retract in the first place...I don't know.

IMO only the pressure plate should function this way, and anything connected to it should work as "DEFAULT" or the owner of the claim. I don't know how feasible that is however...

**Comment by Shmeeb** [comment]
Now thinking about it and looking at the debug I believe I am experiencing the same thing as you sorta, since a player besides the owner loaded the chunk to start the redstone farm/growth and therefore shows up as the "user" that caused it in debug (I think), and has no perms. 

On my test server it seems to work fine since I think I was the one to load the chunk there.

Maybe make a config option to make non player sources (pistons, pressure plates, melon stems, etc) not be affected by flags?

**Comment by bloodmc** [comment]
I'll take a look and see what I can improve =)

**Comment by bloodmc** [comment]
@Shmeeb so what do you want exactly? Do you want a player that enters your area to be able to access your pistons etc? If so, why not give them accesstrust? You can also use '/accesstrust public' which will take care of ALL blocks that do not contain inventory.

**Comment by Shmeeb** [comment]
A config option that makes block changes/places/etc initially caused by non player items (pressure plates, pistons, melon stems, etc.) not be stopped by any flags would be ideal. Owners that want players able to run farms have to set like 10+ flags if they want them to work, which is a tall ask for a newbie imo

**Comment by bloodmc** [comment]
OK so a configurable blacklist that GP flags will ignore correct?

**Comment by Shmeeb** [comment]
Yes that would be amazing

**Comment by bloodmc** [comment]
OK, I'll add a config for this when I get some more free time.

**Comment by bloodmc** [comment]
@Shmeeb Just letting you know that I have started the implementation of this feature. There will be a new config setting called 'id-blacklist' in the flag section of GP's config. You will simply add the id of the item/block/entity you want to blacklist and GP will ignore it. This list will also support meta until it is removed in later MC version.

**Comment by bloodmc** [comment]
So after some thought, I'm thinking of adding a blacklist per flag as there would be many cases where a user would only want to ignore a block/item/entity for a specific flag and not globally. So how is the following 

Global source blacklist - blacklists id's that are the source of event
Global target blacklist - blacklists id's that are the target of event
Blacklist per flag - a blacklist per flag.

Sound good?

**Comment by Shmeeb** [comment]
Perfect 😃
