### ISSUE TITLE
setting a flag as an override stops the flag from working at all

### ISSUE THREAD

**Issue by dezil** [MinecraftPortCentral/GriefPrevention#861]
this is using /cf block-break minecraft:player minecraft:air true override

set as an override https://griefprevention.github.io/debug/?jvhU9Afflk

and this using /cf block-break minecraft:player minecraft:air true

set as a flag just on the claim https://griefprevention.github.io/debug/?2vvLJdo2kC

**Comment by bloodmc** [comment]
Please give exact steps on how air is showing up for break because i explicitly ignore it in GP and was unable to reproduce on clean server. I tested other override flags (not using AIR) and it works fine.

**Comment by bloodmc** [comment]
OK I confirmed AIR shows up with openblocks only since they run their gravestone placement hook during FML's world tick event.

**Comment by bloodmc** [comment]
So the reason AIR shows up is because OpenBlocks schedules their gravestone placement the following tick during FML's WorldTick event. They check if the gravestone location can be modified which GP checks during Pre. So in this case AIR shows up because nothing exists in that location. If GP blindly allowed these checks, it would break a ton of mods so the check must stay in place. 

Here are the steps OpenBlocks/GP take

1. Attempt to find safe location to place grave
https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/PlayerDeathHandler.java#L250
2. This shows up on GP's side as a Pre event since the mod is checking the canPlace method. This is the only listener where AIR is valid check. GP MUST check against AIR breaks as many mods will do this pre(dummy) check to see if they can place a block. If GP blindly ignores this check, it will break many mods.

Blacklist does NOT work since it is impossible for GP to determine what the mod will do during these pre checks.

So with that said, GP is properly handling this to avoid mods from griefing. If you want to allow gravestones to be placed, I would modify openblocks handler or add an exception in GP's source.
