### ISSUE TITLE
The missing Config

### ISSUE THREAD

**Issue by Konix26** [MinecraftPortCentral/GriefPrevention#891]
Hello, I'm Konix. I would like to ask for a few tips on how to fix this issue if at all, or if there is any prior information to be had for fixing this specific issue.

The owner of my server claims that there shouldn't be a claim cap for players however there is one in place. But not only is that a problem, he can't find the config to remove the cap. Weirdly enough, the cap varies from player to player based on subdivisions. Not to mention I could run out of the ability to make subdivisions and still make normal claims, but on my alternate account, I can't make new claims after hitting the subdivision cap. I can't really provide information outside of this, but that's pretty much all I know, either the config is gone, the owner can't find it, or it was placed elsewhere in the plugin's setup but still is being referenced. Though somehow its defaults were altered. Aaanyways this is all the information I have thus far, you can ask any questions and I'll see what kind of response I can pull from the owner.

Much love, appreciate that help if any is provided.
-Konix

**Comment by DrZoddiak** [comment]
`Not to mention I could run out of the ability to make subdivisions and still make normal claims`
https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Advanced-Options
Those are two different options, that's intended, set otherwise if you want them different.

`The owner of my server claims that there shouldn't be a claim cap for players however there is one in place. ` That is also in the "advanced options" link

`I can't really provide information outside of this, but that's pretty much all I know, either the config is gone, the owner can't find it, or it was placed elsewhere in the plugin's setup but still is being referenced. `
It is in (by default) `config/griefprevention/worlds` However as stated above the options you seek are not in the config

`Aaanyways this is all the information I have thus far, `
**always** provide Sponge version + GP version
for all I know you're using a build from 2 years ago.

**Comment by Konix26** [comment]
`Those are two different options, that's intended, set otherwise if you want them different.`
I understand they are different, however you missed:
`but on my alternate account, I can't make new claims after hitting the subdivision cap.`

`**always** provide Sponge version + GP version
for all I know you're using a build from 2 years ago.`
I am unsure I can ask for these bits of information as this owner likely will not want to give them out, however MC version is 1.12.2 and we're likely up to date.

Thank you for the information, I'll look further into it and see what I can find.

-Nick

**Comment by bloodmc** [comment]
Make sure you are using GP 689, SF 3616+ and following linke DrZoddiak stated above.
