### ISSUE TITLE
GriefPrevention Duplication Bug

### ISSUE THREAD

**Issue by Focamacho** [MinecraftPortCentral/GriefPrevention#903]
**1.** Claim somewhere.
**2.** Place a block in the border of the claim.
**3.** Place what you want to dupe outside of the claim, close to the block in the border.
**4.** Tell to another player without permission in the claim place a Long-Range Breaker.
**5.** It's all, see the video for more info.

**Video: https://www.youtube.com/watch?v=NvNTE3dG114**
Reported too in: https://github.com/Ellpeck/ActuallyAdditions/issues/1261

**Comment by bloodmc** [comment]
Dupes are not caused by GP as it merely cancels events. Report dupes to Sponge. For the time being, GP has a config to workaround these issues

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/configuration/category/ClaimCategory.java#L40
