### ISSUE TITLE
enter-claim=false - despawning mobs and animals

### ISSUE THREAD

**Issue by Yorkforce** [MinecraftPortCentral/GriefPrevention#904]
- GP Version: 689
- SpongeForge Version: 3760
- Modpack: SevTech 3.1.1

- Issue:

When setting the enter-claim=false either via config or by changing /cf flag it deletes any mob trying to enter the claim, making claims completely safe from any threats.

Also any animals either by randomly wandering into, or being lead by the player will also despawn instantly.

Turning the enter-claim=true will allow mobs/animals to enter claims normally.

- Expected Behaviour:

The enter-claim flag should only affect other players.

**Comment by kencinder** [comment]
Then you make it affect only other players. If you just change the base `enter-claim` flag, it affects ALL entities.

Use `/cf enter-claim minecraft:player false`

**Comment by Yorkforce** [comment]
The default flags? which are set by the config? Sounds like the config is setting flags.

I understand its possible to make a default flag apply to all claims by running the command ingame, however when you're hosting multiple servers, like say 15+, thats 15+ commands (potentially 45+ if you take into consideration admin/basic/town claims) that need to be ran, instead of just copy/pasting a single config file.

The vast majority of people using grief prevention will be using it specifically to, you know, prevent griefing from 'other players'.
Perhaps an extra config option could be added specifically for enter-claim-players?

**Comment by kencinder** [comment]
Again, the config is not used to set flags. You can change those defaults in it yes, but you can't set new ones in it.
If you want only players blocked using enter-claim, you must do what I said.

Settings them in the config won't happen, that's not how the plugin works.

**Comment by Yorkforce** [comment]
I understand that, my point was its alot of messing about to have to go ingame, set a basic claim up, then run a default flag command, per server, for something that I expect most users of the plugin would be expecting/using as a default setting anyways.

Grief prevention has always been about preventing grief from other players. That is its basic function.

**Comment by kencinder** [comment]
All those defaults in the config are base flags only, they affect source and target. They're akin to setting `block-break any any true default`.
When you want a specific source or target, it is setting a custom flag and is don in game.

The only thing I could suggest with respect to doing it in bulk, is editing `luckperms\sponge-data\defaults\default.json` You would have the following in it for all your servers for example, to stop only players from entering a basic claim as a default flag.

```    {
      "context": {
        "gp_claim_defaults": "basic",
        "world": "world"
      },
      "data": {
        "griefprevention.flag.enter-claim.minecraft.player": false
      }
```

**Comment by Yorkforce** [comment]
I appreciate the potential solution/workaround

but let's look at another scenario

enter-claim=false is something we like to use, it's a great way to prevent grief, if griefers cant enter the claim in most cases they cant get close enough to bypass it using modded items but we like give our players the option, so they can /cf and edit that flag at thier own risk. (This is something inherited by skyclaims btw with the /is lock feature, so the idea behind it is valid)

However, now they can use it to exploit the game and prevent any mobs from attacking them, now they have selective peace mode instead of a difficult and challenging modpack, or if we prevent changing that flag they have a locked down claim they cant show off to anyone, which is just gonna end up with complaints, or worse, they will add people they dont trust to thier claim and end up getting thier claim griefed, resulting in the plugin failing to do what its called due to limited options. (this is not a criticism of GP btw, just pointing out the context of the scenario).

I'm pretty sure the enter claim feature in a plugin thats designed to stop players messing with other players stuff could be changed or adjusted to prevent only players entering, why would preventing mobs and animals, aka the gameplay, from doing whats its suppose to, there is a level of grief caused by the game that is to be expected, what's not expected is another player coming along and being an arsehole and destroying/stealing your stuff through no fault of your own, hence ... grief prevention.

Not really sure why I have to explain this tbh, I thought it would just be obvious.

**Comment by bloodmc** [comment]
> I understand its possible to make a default flag apply to all claims by running the command ingame, however when you're hosting multiple servers, like say 15+, thats 15+ commands (potentially 45+ if you take into consideration admin/basic/town claims) that need to be ran, instead of just copy/pasting a single config file.  


If you do have 15+ servers then you should be running bungeecord with a shared LP database. As all flags are stored in permissions, you simply set whatever permission you want with global context. If you want a permission set to a specific server then you pass the server context.  


> if griefers cant enter the claim in most cases they cant get close enough to bypass it using modded items but we like give our players the option, so they can /cf and edit that flag at thier own risk.  


You can use the `border-block-radius` to add a protected radius around players claims
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/configuration/category/ClaimCategory.java#L40  

As for `enter-claim`, the flag was designed to support all entities for admin use. The flag is not given to users by default since it can be exploited in various ways(not just with blocking animal/monsters). For ex. nothing stops a player from creating a dummy claim with `enter-claim` false near another user claim.

If you still want to allow it for your users, then you do one of the following options 

1. Deny `griefprevention.user.flag.minecraft.animal` and `griefprevention.user.flag.minecraft.monster` on a user group using a global context (assuming shared DB so it affects all servers)
See https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Global-Config#user-claim-flags
Note: This will not affect already set claims. To solve that see next step.
2. Set claim type overrides (using the global context) to force allow `enter-claim` for animal and monster.
3. Create a plugin and use BorderClaimEvent in the API to handle it however you wish.

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/api/java/me/ryanhamshire/griefprevention/api/event/BorderClaimEvent.java

**Comment by bloodmc** [comment]
Update: Option 1 will not work as I would have to add capability to deny using `any` with flags. I'll keep this ticket open for reminder to add improvement for upcoming GriefDefender release.

**Comment by Yorkforce** [comment]
Thanks for the reply, I'll look into the shared database for luckperms, the only reason we don't use it currently is because we host many different modpacks with different plugin setups so it's easier to copy and edit the perms files to the servers requirements, but using a server context option might be tricky, we would still need to specify each server to ensure we don't end up messing with, for example our skyclaim servers.

Wasn't aware of the claim border option, sounds interesting.

Also looking forward to the (new?) GriefDefender release.

All that being said, I do understand the enter claim is suppose to be as useful as possible, I mean for admin claims at our /spawns it's great that it keeps mobs out and it's very useful, but as mentioned above, to apply it specifically to players in just basic claims, its alot of setting up via perms per server/or per server via LP database.
Having an enter-claim-player default flag in the config would essentially replace all that permission set up with a single config option? Makes it much more user friendly.
